<?php

return [
    'industry' => [
        ['name' => 'Accounting'],
        ['name' => 'Advertising'],
        ['name' => 'Agriculture'],
        ['name' => 'Architecture'],
        ['name' => 'Automotive'],
        ['name' => 'Construction'],
        ['name' => 'Consulting'],
        ['name' => 'Education'],
        ['name' => 'Event Planning'],
        ['name' => 'Fashion'],
        ['name' => 'Finance'],
        ['name' => 'Food & Beverage'],
        ['name' => 'Freelance'],
        ['name' => 'Health & Fitness'],
        ['name' => 'Hospitality'],
        ['name' => 'Information Technology'],
        ['name' => 'Insurance'],
        ['name' => 'Legal Services'],
        ['name' => 'Manufacturing'],
        ['name' => 'Marketing'],
        ['name' => 'Media'],
        ['name' => 'Music & Entertainment'],
        ['name' => 'Non-Profit'],
        ['name' => 'Pharmaceuticals'],
        ['name' => 'Real Estate'],
        ['name' => 'Retail'],
        ['name' => 'Shipping & Logistics'],
        ['name' => 'Software Development'],
        ['name' => 'Telecommunications'],
        ['name' => 'Tourism & Travel'],
        ['name' => 'Transportation'],
        ['name' => 'Wholesale'],
        ['name' => 'E-commerce'],
        ['name' => 'Environmental Services'],
        ['name' => 'Human Resources'],
        ['name' => 'Graphic Design'],
        ['name' => 'Pet Services'],
        ['name' => 'Photography'],
        ['name' => 'Publishing'],
        ['name' => 'Research & Development'],
        ['name' => 'Security'],
        ['name' => 'Social Media Marketing'],
        ['name' => 'Sports & Recreation'],
        ['name' => 'Technology'],
        ['name' => 'Transportation'],
        ['name' => 'Wholesale Distribution'],
        ['name' => 'Other'],
    ]
];

